{% set name = "apache-airflow-providers-sftp" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-sftp-{{ version }}.tar.gz
  sha256: 9d03289e3532ae47ef07dea3aa427559322f6d800213ec3758f97c0a4ed928c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - apache-airflow >=2.1.0
    - paramiko >=2.6.0
    - pysftp >=0.2.9
    - python >=3.6
    - sshtunnel >=0.1.4,<0.2

test:
  imports:
    - airflow.providers.sftp
    - airflow.providers.sftp.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for SSH File Transfer Protocol (SFTP) for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
