{% set name = "apache-airflow-providers-sftp" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-sftp-{{ version }}.tar.gz
  sha256: f8c0aefd55188d843d302f4a454ad9d5f995c1d064655cb812c7221bba3cc157

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.2.0
    - apache-airflow-providers-ssh >=2.1.0
    - paramiko >=2.6.0
    - pysftp >=0.2.9
    - sshtunnel >=0.3.2

test:
  imports:
    - airflow.providers.sftp
    - airflow.providers.sftp.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-sftp package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-sftp/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
